spring.datasource.url=jdbc:mysql://localhost:3306/hms_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=13090802
spring.jpa.show-sql=true

app.jwt.secret=dev-secret-key-only-for-local-use-minimum-64-characters-long-ok
app.jwt.expiration-ms=900000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method


logging.level.root=INFO
logging.level.com.saad.hms=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.jpa.open-in-view=false